### ISSUE TITLE
Rails server + logs

### ISSUE THREAD

**Issue by joelbrewer** [theblacksmith/vagrant-sharetribe-box#1]
Hey, I've setup a local install of sharetribe using your vagrant box.. and it's working great! Thanks for putting that together. However, I'm wondering how to access the logs for my rails server. It seems like your script is automatically starting a rails server process.. but I am unable to find where in your code that is actually happening.

**Comment by joelbrewer** [comment]
Ah. I think I figured it out. Looks like we're using Passenger + Nginx and the logs are being written to standard out, which is picked up by the passenger log file.

**Comment by svallory** [comment]
I'm glad you liked it. And yes, we are using Nginx + Passenger. The box is configured using chef. Specifically the [Sharetribe cookbook](https://github.com/theblacksmith/sharetribe-cookbook) I created. Check out [the http recipe](https://github.com/theblacksmith/sharetribe-cookbook/blob/master/recipes/http-server.rb) and
[the nginx-site.erb template](https://github.com/theblacksmith/sharetribe-cookbook/blob/master/templates/nginx-site.erb)
